version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
#      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - IMAGE_NAME="demo"
      - REPOSITORY_URI=public.ecr.aws/q2m2k6m3/demo
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo Image_tag 
      - docker build -t public.ecr.aws/q2m2k6m3/demo:latest
      - docker tag public.ecr.aws/q2m2k6m3/demo:latest 014125565833.dkr.ecr.eu-central-1.amazonaws.com/public.ecr.aws/q2m2k6m3/demo:latest 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
  #    - docker push $REPOSITORY_URI:latest
      - docker push 014125565833.dkr.ecr.eu-central-1.amazonaws.com/public.ecr.aws/q2m2k6m3/demo:latest
      - echo Writing image definitions file...
     
